const auctionAddress = "0x87dCaE081479f527F3237e532fc3d2427113F77F";
const auctionAbi = [
	{
		inputs: [
			{ internalType: "address", name: "_standardToken", type: "address" },
			{ internalType: "address", name: "_standardNFT", type: "address" },
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "previousOwner",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
		],
		name: "OwnershipTransferred",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "nftID",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "finalPrice",
				type: "uint256",
			},
		],
		name: "newAuctionClosed",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "nftID",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "startTime",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "endTime",
				type: "uint256",
			},
		],
		name: "newAuctionOpened",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "nftID",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "address",
				name: "bidder",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "bidPrice",
				type: "uint256",
			},
		],
		name: "newPlaceBid",
		type: "event",
	},
	{ stateMutability: "payable", type: "fallback" },
	{
		inputs: [{ internalType: "uint16", name: "", type: "uint16" }],
		name: "auctions",
		outputs: [
			{ internalType: "uint256", name: "nftID", type: "uint256" },
			{ internalType: "uint256", name: "startTime", type: "uint256" },
			{ internalType: "uint256", name: "endTime", type: "uint256" },
			{ internalType: "uint256", name: "currentBid", type: "uint256" },
			{ internalType: "address", name: "currentBidder", type: "address" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "balances",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint8", name: "_status", type: "uint8" }],
		name: "changeStatus",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "checkStatus",
		outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "closeAuction",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "contractState",
		outputs: [
			{ internalType: "enum MdAuction.AuctionState", name: "", type: "uint8" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "durationAuction",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "entranceFee",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getBalance",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "", type: "address" },
			{ internalType: "address", name: "", type: "address" },
			{ internalType: "uint256", name: "", type: "uint256" },
			{ internalType: "bytes", name: "", type: "bytes" },
		],
		name: "onERC721Received",
		outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
		stateMutability: "pure",
		type: "function",
	},
	{
		inputs: [],
		name: "openAuction",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "owner",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
		name: "placeBid",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [],
		name: "renounceOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "_durationAuction", type: "uint256" },
		],
		name: "setDurationAuction",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "_entranceFee", type: "uint256" },
		],
		name: "setEntranceFee",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_standardNFT", type: "address" },
		],
		name: "setStandardNFT",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_standardToken", type: "address" },
		],
		name: "setStandardToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "", type: "address" }],
		name: "tokenBalances",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
		name: "transferOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "withdraw",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{ stateMutability: "payable", type: "receive" },
];
module.exports = { auctionAddress, auctionAbi };

// const auctionAddress = "0xd5e3D5841FA8425F160c5e65c28f42843E62843D";
// const auctionAbi = [
// 	{
// 		inputs: [
// 			{ internalType: "address", name: "_standardToken", type: "address" },
// 			{ internalType: "address", name: "_standardNFT", type: "address" },
// 		],
// 		stateMutability: "nonpayable",
// 		type: "constructor",
// 	},
// 	{
// 		anonymous: false,
// 		inputs: [
// 			{
// 				indexed: true,
// 				internalType: "address",
// 				name: "previousOwner",
// 				type: "address",
// 			},
// 			{
// 				indexed: true,
// 				internalType: "address",
// 				name: "newOwner",
// 				type: "address",
// 			},
// 		],
// 		name: "OwnershipTransferred",
// 		type: "event",
// 	},
// 	{
// 		anonymous: false,
// 		inputs: [
// 			{
// 				indexed: false,
// 				internalType: "uint256",
// 				name: "nftID",
// 				type: "uint256",
// 			},
// 			{
// 				indexed: false,
// 				internalType: "uint256",
// 				name: "startTime",
// 				type: "uint256",
// 			},
// 			{
// 				indexed: false,
// 				internalType: "uint256",
// 				name: "endTime",
// 				type: "uint256",
// 			},
// 		],
// 		name: "newAuctionOpened",
// 		type: "event",
// 	},
// 	{ stateMutability: "payable", type: "fallback" },
// 	{
// 		inputs: [{ internalType: "uint16", name: "", type: "uint16" }],
// 		name: "auctions",
// 		outputs: [
// 			{ internalType: "uint256", name: "nftID", type: "uint256" },
// 			{ internalType: "uint256", name: "startTime", type: "uint256" },
// 			{ internalType: "uint256", name: "endTime", type: "uint256" },
// 			{ internalType: "uint256", name: "currentBid", type: "uint256" },
// 			{ internalType: "address", name: "currentBidder", type: "address" },
// 		],
// 		stateMutability: "view",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "balances",
// 		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
// 		stateMutability: "view",
// 		type: "function",
// 	},
// 	{
// 		inputs: [{ internalType: "uint8", name: "_status", type: "uint8" }],
// 		name: "changeStatus",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "checkStatus",
// 		outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
// 		stateMutability: "view",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "closeAuction",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "contractState",
// 		outputs: [
// 			{ internalType: "enum MdAuction.AuctionState", name: "", type: "uint8" },
// 		],
// 		stateMutability: "view",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "durationAuction",
// 		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
// 		stateMutability: "view",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "entranceFee",
// 		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
// 		stateMutability: "view",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "getBalance",
// 		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
// 		stateMutability: "view",
// 		type: "function",
// 	},
// 	{
// 		inputs: [
// 			{ internalType: "address", name: "", type: "address" },
// 			{ internalType: "address", name: "", type: "address" },
// 			{ internalType: "uint256", name: "", type: "uint256" },
// 			{ internalType: "bytes", name: "", type: "bytes" },
// 		],
// 		name: "onERC721Received",
// 		outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
// 		stateMutability: "pure",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "openAuction",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "owner",
// 		outputs: [{ internalType: "address", name: "", type: "address" }],
// 		stateMutability: "view",
// 		type: "function",
// 	},
// 	{
// 		inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
// 		name: "placeBid",
// 		outputs: [],
// 		stateMutability: "payable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "renounceOwnership",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [
// 			{ internalType: "uint256", name: "_durationAuction", type: "uint256" },
// 		],
// 		name: "setDurationAuction",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [
// 			{ internalType: "uint256", name: "_entranceFee", type: "uint256" },
// 		],
// 		name: "setEntranceFee",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [
// 			{ internalType: "address", name: "_standardNFT", type: "address" },
// 		],
// 		name: "setStandardNFT",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [
// 			{ internalType: "address", name: "_standardToken", type: "address" },
// 		],
// 		name: "setStandardToken",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [{ internalType: "address", name: "", type: "address" }],
// 		name: "tokenBalances",
// 		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
// 		stateMutability: "view",
// 		type: "function",
// 	},
// 	{
// 		inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
// 		name: "transferOwnership",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{
// 		inputs: [],
// 		name: "withdraw",
// 		outputs: [],
// 		stateMutability: "nonpayable",
// 		type: "function",
// 	},
// 	{ stateMutability: "payable", type: "receive" },
// ];
// module.exports = {
// 	auctionAddress,
// 	auctionAbi,
// };
