const auctionAddress = "0x93d59257BB4D02D672CFfc4EA3f381C58137f533";
const auctionAbi = [
	{
		inputs: [
			{ internalType: "address", name: "_token", type: "address" },
			{ internalType: "address", name: "_nft", type: "address" },
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "previousOwner",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
		],
		name: "OwnershipTransferred",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "nftId",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "finalPrice",
				type: "uint256",
			},
		],
		name: "newAuctionClosed",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "nftId",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "startTime",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "endTime",
				type: "uint256",
			},
		],
		name: "newAuctionOpened",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "nftId",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "address",
				name: "bidder",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "bidPrice",
				type: "uint256",
			},
		],
		name: "newPlaceBid",
		type: "event",
	},
	{ stateMutability: "payable", type: "fallback" },
	{
		inputs: [],
		name: "auctionLength",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		name: "auctions",
		outputs: [
			{ internalType: "uint256", name: "nftId", type: "uint256" },
			{ internalType: "uint256", name: "startTime", type: "uint256" },
			{ internalType: "uint256", name: "endTime", type: "uint256" },
			{ internalType: "uint256", name: "currentBid", type: "uint256" },
			{ internalType: "address", name: "currentBidder", type: "address" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint8", name: "_state", type: "uint8" }],
		name: "changeState",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "checkStatus",
		outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "closeAuction",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "contractState",
		outputs: [
			{ internalType: "enum MdAuction.AuctionState", name: "", type: "uint8" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "durationAuction",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "entranceFee",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getBalances",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "operator", type: "address" },
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "uint256", name: "tokenId", type: "uint256" },
			{ internalType: "bytes", name: "data", type: "bytes" },
		],
		name: "onERC721Received",
		outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
		stateMutability: "pure",
		type: "function",
	},
	{
		inputs: [{ internalType: "string", name: "_uri", type: "string" }],
		name: "openAuction",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "owner",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
		name: "placeBid",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [],
		name: "renounceOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_nft", type: "address" }],
		name: "setStandardNFT",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_token", type: "address" }],
		name: "setStandardToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
		name: "transferOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{ stateMutability: "payable", type: "receive" },
];

module.exports = {
	auctionAddress,
	auctionAbi,
};
